### ISSUE TITLE
Image is not getting pulled in windows machine for version 2

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/DataConnector#1]
Hi,

Trying to pull docker image using 'Start' from DC. It throws message "Docker Alert - Unable to start docker". 
**Windows machine
Version 2 exe shared on 11 August** 

Attaching screenshot below

![DC_DockerNotRunning](https://user-images.githubusercontent.com/105902516/184124119-25127158-e721-42c8-94b6-d3d3edbab875.jpg)

**Comment by SumedhaBhosale** [comment]
Tried to pull docker image with same exe on PIPL01 machine, gave me same error message.

**Comment by chandkc** [comment]
5adc48759a79d6b52a08ab01d3ba8009e7dc7cbb Mon Sep 17 00:00:00 2001
Committed
