### ISSUE TITLE
Unable to pull no-gpu image from graphical interface

### ISSUE THREAD

**Issue by sujitpre** [chandkc/DataConnector#13]
I could not pull image from Prins installer interface. i had do it from terminal using "docker pull prescience/prins_no_gpu:v2" 
![Screenshot from 2022-09-15 12-21-00](https://user-images.githubusercontent.com/105837333/190336931-0d3001b7-6c0d-43ca-8779-bebf3eece59b.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  80f062b
