### ISSUE TITLE
Unable to connect server

### ISSUE THREAD

**Issue by sujitpre** [chandkc/DataConnector#14]
![Screenshot from 2022-09-15 17-57-28](https://user-images.githubusercontent.com/105837333/190443604-74c4d645-1d50-42e5-bbe6-9cf4352e4c60.png)
![Screenshot from 2022-09-15 17-54-27](https://user-images.githubusercontent.com/105837333/190444134-0e6ec46e-f6fa-406b-880f-47712c812e7d.png)

**Comment by bishweshwarShome** [comment]
can you reproduced the issue ?

**Comment by bishweshwarShome** [comment]
source of error SSH connection refused.
