### ISSUE TITLE
IO directory path and port number fields disabled in DC

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/DataConnector#15]
Hi,

Test_V_D_2_9_Windows EXE shared on 16 Sep 
Window machine

![DC_IODIRPath](https://user-images.githubusercontent.com/105902516/190595713-53ac1ced-c681-4209-92cb-f512bdaa57b9.png)

After download, when we open the software in Local Docker Environment Parameters these (IO DIR and port number) fields are disabled.  If I want to change the IO dir, how to initate this process?

**Comment by bishweshwarShome** [comment]
If any PRinS3 container is running with correct version image, then we take the IO directory and port from there and both fields are disabled.

**Comment by SumedhaBhosale** [comment]
Okay. Thank you !
@LobeliaG and @prescienceit  - Please put this in as help here.
