### ISSUE TITLE
Unable to connect to distinct GPU machine through DC

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/DataConnector#17]
Hi,

Windows machine
PIPL01 

I was trying to connect PIPL01 to 02 (GPU machine, ubuntu 18 with new prins version 2 image). Somehow it showed server connected with v1 image in DC while in 02 machine - v2 image was running and gromacs command was unrecognized. 

![PIPL02_GPU](https://user-images.githubusercontent.com/105902516/192525787-43c54c91-45dd-4a49-a0c5-717b2993d172.png)

**Comment by bishweshwarShome** [comment]
new image required with version tag @prescienceit 

for now, testing version with gmx.
