### ISSUE TITLE
Unable to recognize server 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/DataConnector#18]
Hi,

Windows machine
PIPL01

Here, DC is unable to recognize docker server running at PIPL02 and says server is offline. 

![PIPL02_DockerServer](https://user-images.githubusercontent.com/105902516/192526514-3c253b14-a234-4d59-9e57-34edb85a8764.png)

**Comment by bishweshwarShome** [comment]
It's showing because this two machines are connected to two different networks may be.

**Comment by bishweshwarShome** [comment]
can you reproduced the issue ?

**Comment by bishweshwarShome** [comment]
Now it's working fine.
