### ISSUE TITLE
From DC:  the image pulling process is taking a long time on pipl08.

### ISSUE THREAD

**Issue by sanvidat** [chandkc/DataConnector#22]
1. taking 2 hour for non gpu image(size 15GB)
2. connected with pipl_spectra net speed-180 mbps
![Screenshot from 2022-09-28 11-58-30](https://user-images.githubusercontent.com/105784499/192705002-6526ed0b-4155-43e7-a8c2-38a9aff8a3d2.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id :  80f062b
