### ISSUE TITLE
Unable to pull gpu image from user interface (PRinS_D_V_HA_2 installer)

### ISSUE THREAD

**Issue by sujitpre** [chandkc/DataConnector#26]
It shows the message ' started pulling image'. But, there is no change in volume of the directory which is assigned for storing the image. 

![Screenshot from 2022-09-28 11-22-06](https://user-images.githubusercontent.com/105837333/192932617-7b169bb3-33fe-432b-bafe-6993932f1680.png)
![Screenshot from 2022-09-28 11-30-41](https://user-images.githubusercontent.com/105837333/192932767-9344478d-8aa0-4b31-b21e-0950c539935e.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  80f062b
