### ISSUE TITLE
If more than one image is found, start button is unable to run docker container.

### ISSUE THREAD

**Issue by sanvidat** [chandkc/DataConnector#31]
Images found
1.prescience/prins_no_gpu
2. prescience/prins_2_gpu

![dc_start](https://user-images.githubusercontent.com/105784499/193506739-044b734c-00bf-4ea9-b555-efb398b4bf72.png)

**Comment by sanvidat** [comment]
![terminal](https://user-images.githubusercontent.com/105784499/193507237-676281a6-9bdd-4c2d-b546-f2621179171b.png)

**Comment by bishweshwarShome** [comment]
update in next version, 
1. gpu to non-gpu (new settings)

**Comment by bishweshwarShome** [comment]
Can be fixed.
