### ISSUE TITLE
Error: Auto Addtion of localhost 

### ISSUE THREAD

**Issue by sanvidat** [chandkc/DataConnector#36]
I ran docker with port number 8081, docker is running but the added localhost is offline.
![dc_sc](https://user-images.githubusercontent.com/105784499/195564159-e3c21831-2456-4c30-b9fe-9b2752a75790.png)

**Comment by sanvidat** [comment]
port number - 8081
![dc_io](https://user-images.githubusercontent.com/105784499/195564288-4da734b1-0f44-47db-80e7-bd08f645ee3e.png)

**Comment by sanvidat** [comment]
Docker running 
![docker_run](https://user-images.githubusercontent.com/105784499/195564442-d63ebb1d-831e-4d68-834f-7e3190d8a341.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id :  9c7d3b2
