### ISSUE TITLE
The software frozen during checking of gromas inside container

### ISSUE THREAD

**Issue by sujitpre** [chandkc/DataConnector#39]
Both Nvidia-driver and gpu docker (in non-root pathway) were already installed in the host system . But, currently Nvidia-driver is not working (NVIDIA-SMI has failed). I am working with V2_TEST installer which is shared with me on 23.1.2023. The Host I/O directory is configured. After clicking the "Data Communicator" it shows a message that "Prins3 image found". Then after clicking start button, it displays "Checking gromacs inside container.". But, it does not proceed any more.
![Screenshot from 2023-01-23 18-35-05](https://user-images.githubusercontent.com/105837333/214048151-574cc0e9-f459-46f5-8135-680fce810a8e.png)
![Screenshot from 2023-01-23 18-43-44](https://user-images.githubusercontent.com/105837333/214048517-6a13acea-7f6e-46ba-b5a9-575291f62902.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id: 529fdb9
