### ISSUE TITLE
Administrator Rights to run EXE on windows

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/DataConnector#4]
Hi,

To run exe on windows machine, user has to do right click "Run as administrator". What if some silly user just double-clicked it ? It throws error saying Unhandled exception .... [In a Language not understandable to non-technical person]
So, it would be better if we put some message displaying that !

**Comment by chandkc** [comment]
1. Recommended to install the PRINS3 exe outside the 'Program Files' Directory.
@LobeliaG Mention this in the Windows installation part (Manual)

**Comment by LobeliaG** [comment]
> 1. Recommended to install the PRINS3 exe outside the 'Program Files' Directory.
>    @LobeliaG Mention this in the Windows installation part (Manual)

Okay sir.
