### ISSUE TITLE
issue in gromacs configuration inside container

### ISSUE THREAD

**Issue by sujitpre** [chandkc/DataConnector#40]
After reinstalling the cuda, and nvidia-docker, the V2_TEST installer was launched. Local docker environment parameter was already configured. After clicking the data communicator, it shows that container is running, prins_2_gpu:v2 image found. **But, the gromacs is not configured properly**. 
Then the gromacs2021_5 had to configure manually,  the status was checked again. But, it was displaying  "checking gromacs inside container" in log section but could not proceed any more. I again relaunched the installer and filled connection method section and again checked status. But, this time also same installer was stuck into checking gromacs. Then I reopened the installer  and checked the status again. This time it shows the message " inside container NVIDIA and gromacs working properly" 

![Screenshot from 2023-01-24 17-11-13](https://user-images.githubusercontent.com/105837333/214317992-08d5e696-483d-42a0-a4e7-e322d9351068.png)
![Screenshot from 2023-01-24 18-28-14](https://user-images.githubusercontent.com/105837333/214318399-db1765c9-b0f8-4a44-92db-b82481657390.png)
![Screenshot from 2023-01-24 18-32-26](https://user-images.githubusercontent.com/105837333/214318545-ba26495a-7085-4833-830a-86fbc27f026e.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id: 529fdb9
