### ISSUE TITLE
Not showing status 

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/DataConnector#42]
**Version** - PRinS3_V_2_1_0_Ubuntu_2020_64x (Internal release)
**OS** - Linux
**Machine** - PIPL03

The online status doesn't appears. This is seen in GPU image

![Screenshot from 2023-02-24 14-47-30](https://user-images.githubusercontent.com/117424735/221140637-2e73ca47-7fb0-4f6b-9b25-ed348f52ae22.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  529fdb9
