### ISSUE TITLE
Stuck in checking nvidia and  gromacs inside container (more than 5 minutes)

### ISSUE THREAD

**Issue by sujitpre** [chandkc/DataConnector#43]
![Screenshot from 2023-03-01 09-51-21](https://user-images.githubusercontent.com/105837333/222045750-4831504e-c983-41d7-baaa-32aafc60a19e.png)
![Screenshot from 2023-03-01 09-51-33](https://user-images.githubusercontent.com/105837333/222045806-bef3c1bd-ca77-408c-b4b5-e530493aca75.png)
![Screenshot from 2023-03-01 09-58-59](https://user-images.githubusercontent.com/105837333/222045847-fe184c29-e522-49a5-bb0d-d6efd25220ff.png)
![Screenshot from 2023-03-01 10-06-28](https://user-images.githubusercontent.com/105837333/222045897-2bdccede-ef20-49f6-a830-b2f44f4a5955.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  529fdb9
