### ISSUE TITLE
GC instances

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/DataConnector#44]
**Version** - PRinS3_V_2_1_0_Ubuntu_2020_64x
 **OS** - Linux

1. The maximum instances allowed is 5 but for **n2d highcpu128** I am only getting 1 instance. 
2. When 1 instance for **n2d highcpu128** is running during that time only 3 instance of n2d highcpu32 is coming even after selecting 4 instances.

![Screenshot from 2023-03-01 11-46-44](https://user-images.githubusercontent.com/117424735/222100359-538e4a5e-870b-4453-9017-7c3d014278c3.png)

**Comment by bishweshwarShome** [comment]
fixed

commit id: b9c12d7
