### ISSUE TITLE
"GROMACS not configured properly" issue

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/DataConnector#45]
Version - PRinS3_V_2_1_0_Ubuntu_2020_64x
OS - Linux
Machine - PIPL03

1. The data connector gives "GROMACS is not configured properly" when installed for the first time (GPU image was already present)
2. When I restarted the system then it was working fine. The same thing was observed in PIPL07 also.

**ERROR**
![Screenshot from 2023-04-13 13-14-43](https://user-images.githubusercontent.com/117424735/231970374-8dc4c925-c376-4ea3-a6b7-b84278b71b26.png)

**NO ERROR**
![Screenshot from 2023-04-13 14-23-06](https://user-images.githubusercontent.com/117424735/231970549-96f11a3f-6c92-4254-9b75-cc208b0af458.png)

**Comment by bishweshwarShome** [comment]
fixed

commit id: 206d5c3
