### ISSUE TITLE
Docker Launch Very First Time

### ISSUE THREAD

**Issue by mdaakhan** [chandkc/DataConnector#6]
While Launching The docker very first time from a windows machine it shows a docker message of successfully download but the container not started

**Comment by bishweshwarShome** [comment]
For the very first time, after pulling the image,

" Image Pull Successful.
Press the START button to starting the container. "

this is the info message.

**Comment by mdaakhan** [comment]
After pulling it should start the container else no means of the start button,
The button can be separated (Status, Download, Start, Stop) Hide the button instead of disabling it

**Comment by bishweshwarShome** [comment]
fixed

**Comment by bishweshwarShome** [comment]
fixed and committed 1d8a938
