### ISSUE TITLE
DC- Docker Status

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/DataConnector#8]
Hi,

 If we check "Status" of docker container, It keeps running and never stops. I clicked status button on ~10.30 am and it was running like that for more than 2 - 3 hours. Screenshot is taken ~2 pm. Please check !

Linux OS 
Exe shared on 24 August 

![DC_Status](https://user-images.githubusercontent.com/105902516/186589912-d34a5457-dd5e-41da-b587-113eb7d8a12e.png)

**Comment by bishweshwarShome** [comment]
fixed

**Comment by bishweshwarShome** [comment]
committed. 
ID: 19226ea
