### ISSUE TITLE
DC - status tab not enabled

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/DataConnector#9]
Hi,

EXE - dated 27 Aug
Linux machine

Attaching screenshot. Please check !
![DC_Status](https://user-images.githubusercontent.com/105902516/187078637-467c13e5-6176-47ee-bdf9-17cea4b2b331.png)

**Comment by bishweshwarShome** [comment]
fixed

**Comment by bishweshwarShome** [comment]
committed, 

ID: bf512e1
